LOCAL_PATH := .
include $(CLEAR_VARS)
include $(GAPPS_CLEAR_VARS)
LOCAL_MODULE := BatteryUsage
LOCAL_PACKAGE_NAME := com.google.android.apps.turbo

GAPPS_LOCAL_OVERRIDES_MIN_VARIANT :=
GAPPS_LOCAL_OVERRIDES_PACKAGES :=

include $(BUILD_GAPPS_PREBUILT_APK)
